@startuml JugadorTieneAnuladorPeroNoExclusividad
skinparam monochrome true
hide footbox
skinparam classAttributeIconSize 0


actor "actual:Jugador" as ja
participant "ba:BotonAnulador" as ba
participant "anulador:Anulador" as an
participant "be:BotonExclusividad" as be
participant "exclusividad:ModificadorGlobalBase" as ex


create ba
ja -> ba: BotonAnulador(anulador)
activate ba
    ba -> an: getClass()
    note right
    como el jugador no usó su
    anulador aún, tiene guardado
    un objeto Anulador y el botón
    no se desactiva
    endnote
    activate an

        ba <-- an: Anulador

    deactivate an

deactivate ba

ja -> be: BotonExclusividad(exclusividad)
activate be

    be -> ex: getClass()

    activate ex
        be <-- ex: ModificadorGlobalBase
    deactivate ex
        note left
        como el jugador ya usó su
        exclusividad, tiene guardado
        un ModificadorGlobalBase por lo que
        el botón se desactiva
        endnote
    be -> be: desactivar()

@enduml