@startuml jugarRondaDePreguntas
skinparam monochrome true
hide footbox
skinparam classAttributeIconSize 0


actor "Controlador" as cr
participant ":AlgoHoot" as ah

participant ":RondaDePreguntas" as rp
participant "puntajes:List" as puntajes
participant "pu:PuntajeParcial" as pu
participant "j:Jugador" as j
participant "pr:PreguntaVF" as pr
participant ":OpcionCorrecta" as oc



cr -> ah: jugarRondaDePreguntas(j, modsInd,\n modsGlob, respuesta)
ah -> rp: jugar(j, modsInd,\n modsGlob, respuesta)
note left
    modsInd es una lista
    de ModificadorIndividual
    (Duplicador, Triplicador)
    modsGlob es una lista
    de ModificadorGlobal
    (Anulador, Exclusividad)
endnote
activate rp
    rp -> pr: responder(respuesta)
        activate pr
            pr -> oc: puntuar(respuesta)
            create pu
            activate oc
                oc -> pu: new PuntajeParcial(1)
                pr <-- oc: pu
                note left
                    El jugador responde
                    correctamente, entonces
                    se puntua con un punto
                endnote
            deactivate oc
        pr --> rp: pu
        deactivate pr

    rp -> pu: establecerJugador(jug)
    activate pu
    deactivate pu
    loop para cada ModificadorIndividual "m" de modsInd
        rp -> pu :agregarModificador(m)
        activate pu
        deactivate pu

        rp -> j: gastar(m)
        activate j
        deactivate j

    end
    loop para cada ModificadorGlobal "m" de modsGlob
            rp -> rp: almacenar(m)
            rp -> j: gastar(m)
            activate j
            deactivate j

        end


@enduml