@startuml terminarRondaDePreguntas
skinparam monochrome true
hide footbox
skinparam classAttributeIconSize 0


actor "Controlador" as test
participant ":AlgoHoot" as ah
participant ":RondaDePreguntas" as r
participant ":Exclusividad" as ex
participant ":Anulador" as an
participant ":PuntajeParcial" as uP
participant "listaPP:ListaDePuntajeParcial" as pp


test -> ah: terminarRondaDePreguntas()
activate ah
ah -> r: terminar()
activate r
    loop por cada modificador global usado en la ronda
        alt es Exclusividad
        r -> ex: aplicar(listaPP)
        activate ex
            ex -> pp: contarPuntajesNoNulos()
            activate pp
            ex <-- pp: cantidadPuntajesNulos
            deactivate pp
                alt cantidadPuntajesNulos == 1
                    loop para cada puntaje de la lista

                    ex -> uP: agregarModificador(new Duplicador())
                    activate uP
                    deactivate uP
                    note left
                        se agrega un
                        Duplicador
                        (multilpicador x2)
                        a la lista de
                        modificadores
                        del puntaje
                    endnote
                    end


                end


        deactivate ex

        end
        alt es Anulador
        r -> an: aplicar(listaPP)
        activate an
            loop para cada jugador que no haya usado el Anulador
                an -> uP: agregarModificador(new ModificadorNulo())
                note left
                    se agrega un
                    ModificadorNulo
                    (multilpicador x0)
                    a la lista de
                    modificadores
                    del puntaje
                endnote
                activate uP
                deactivate uP
            end
        deactivate an
        end
    end
    loop por cada puntaje parcial
        r -> uP: sumarAlPuntajeDelJugador()
        activate uP
        deactivate uP
    end
deactivate r
@enduml