@startuml test04jugarUnTurnoUsandoExclusividadModificaCorrectamenteElPuntaje
skinparam monochrome true
hide footbox
skinparam classAttributeIconSize 0
actor "TestCase" as test
participant ":AlgoHoot" as ah
participant ":RondaDePreguntas" as r
participant ":ModificadorGlobal" as mg
participant ":PuntajeParcial" as pp
cr -> ah: terminarRondaDePreguntas()
activate ah
ah -> r: terminar()
activate r
    loop por cada modificador global usado en la ronda
        r -> mg: modificar(listaPuntajesParciales)
        activate mg
        deactivate mg
    end
    loop por cada puntaje parcial
        r -> pp: sumarAlPuntajeDelJugador()
        activate pp
        deactivate pp
    end
deactivate r
@enduml