@startuml


package Modelo <<Frame>> {

}


package Modelo.Preguntas {
}
package Modelo.Fabricas {
}
package Modelo.Puntuacion {
}
package Modelo.AlgoHoot {
}

package Modelo.Respuestas {

}

package Modelo.Puntuacion.Modificadores {

}
package Modelo.Puntuacion.Puntajes {

}



AlgoHoot ..> Fabricas
Fabricas ..> Preguntas
Puntajes ..> Modificadores
Modificadores ..> Puntajes
AlgoHoot ..> Respuestas
Preguntas .> Respuestas
Fabricas ..> Respuestas
Preguntas ..> Puntajes
Respuestas ..> Puntajes

Puntuacion ..> AlgoHoot
AlgoHoot .left.> Puntuacion




@enduml