@startuml


package Modelo <<Frame>> {

}


package Modelo.Preguntas {
}
package Modelo.Fabricas {
}
package Modelo.Puntuacion {
}
package Modelo.AlgoHoot {
}

package Modelo.Puntuacion.Modificadores {

}
package Modelo.Puntuacion.Puntajes {

}



AlgoHoot .left.> Fabricas
Fabricas ..> Preguntas
Puntajes ..> Modificadores
Modificadores ..> Puntajes
AlgoHoot ..> Preguntas
Preguntas ..> Puntajes


Puntuacion .left.> AlgoHoot
AlgoHoot .left.> Puntuacion




@enduml