@startuml


package Modelo <<Frame>> {

}


package Modelo.Preguntas {
}
package Modelo.Fabricas {
}
package Modelo.Puntuacion {
}
package Modelo.AlgoHoot {
}

package Modelo.Preguntas.Respuestas {

}

package Modelo.Puntuacion.Modificadores {

}
package Modelo.Puntuacion.Puntajes {

}
package Vistas {


}

package Controladores {

}

AlgoHoot -right-> Puntajes
AlgoHoot -left-> Preguntas
AlgoHoot ..> Fabricas
Puntajes --> AlgoHoot
Fabricas ..> Preguntas
Puntajes --> Modificadores
AlgoHoot --> Modificadores
'AlgoHoot ..> Respuestas
'Preguntas -> Respuestas
'Fabricas ..> Respuestas
Preguntas ..> Puntajes



Modelo .up.> Vistas
Controladores .down.> Modelo
Vistas .right.> Controladores
Controladores .left.> Vistas











@enduml