@startuml
'https://plantuml.com/class-diagram

package Preguntas {


interface Pregunta {
    + getPregunta(): String
    + getOpciones(): List<Opcion>
    + responder(rtas: List<Respuesta>): PuntajeParcial
    + getTipo():String
    + getTematica(): String
    + getTextoRespuesta(): String
}

class PreguntaVF {
    - pregunta:String
    - opcionCorrecta:OpcionCorrecta
    - opcionIncorrecta:OpcionIncorrecta
    - tematica: String
    - textoRespuesta: String
    + PreguntaVF(p:String, t:String, rta:String,\nopC:OpcionCorrecta, opI:OpcionIncorrecta)
    + getPregunta(): String
    + getOpciones(): List<Opcion>
    + getTipo():String
    + getTematica():String
    + getTextoRespuesta(): String
    + responder(rtas: List<Respuesta>): PuntajeParcial
}

class PreguntaVFPenalidad{
    - pregunta:String
    - opcionCorrecta:OpcionCorrecta
    - opcionIncorrecta:OpcionIncorrecta
    - tematica: String
    - textoRespuesta: String
    + PreguntaVFPenalidad(p:String, t:String, rta:String,\nopC:OpcionCorrecta, opI:OpcionIncorrecta)
    + getPregunta(): String
    + getOpciones(): List<Opcion>
    + getTipo():String
    + getTematica():String
    + getTextoRespuesta(): String
    + responder(rtas: List<Respuesta>): PuntajeParcial
}

class PreguntaMC {
    - pregunta:String
    - opciones: List<Opcion>
    - tematica: String
    - textoRespuesta: String
    + PreguntaMC(p:String, t:String, rta:String,\n ops:List<Opcion>)
    + getPregunta(): String
    + getOpciones(): List<Opcion>
    + responder(rtas: List<Respuesta>):PuntajeParcial
    + getTipo():String
    + getTematica():String
    + getTextoRespuesta(): String
}

class PreguntaMCParcial {
    - pregunta:String
    - opciones: List<Opcion>
    - tematica: String
    - textoRespuesta: String
    + PreguntaMCParcial(p:String, t:String, rta:String,\n ops:List<Opcion>)
    + getPregunta(): String
    + getOpciones(): List<Opcion>
    + responder(rtas: List<Respuesta>):PuntajeParcial
    + getTipo():String
    + getTematica():String
    + getTextoRespuesta(): String
}

class PreguntaMCPenalidad {
    - pregunta:String
    - opciones: List<Opcion>
    - tematica: String
    - textoRespuesta: String
    + PreguntaMCPenalidad(p:String, t:String, rta:String,\n ops:List<Opcion>)
    + getPregunta(): String
    + getOpciones(): List<Opcion>
    + responder(rtas: List<Respuesta>):PuntajeParcial
    + getTipo():String
    + getTematica():String
    + getTextoRespuesta(): String
}

class PreguntaOC {
    - pregunta:String
    - opciones: List<Opcion>
    - ordenCorrecto: Orden
    - tematica: String
    - textoRespuesta: String
    + PreguntaOC(p:String, t:String, rta:String,\n ops:List<Opcion>
    + getPregunta(): String
    + getOpciones(): List<Opcion>
    + responder(rtas: List<Respuesta>): PuntajeParcial
    + getTipo():String
    + getTematica():String
    + getTextoRespuesta(): String
}

class PreguntaGC {
    - pregunta:String
    - unGrupo: Grupo
    - otroGrupo: Grupo
    - tematica: String
    - textoRespuesta: String
    + PreguntaGC(p:String, t:String, rta:String,\n unGrupo:Grupo, otroGrupo:Grupo)
    + getPregunta(): String
    + getOpciones(): List<Opcion>
    + responder(rtas: List<Respuesta>): PuntajeParcial
    + getTipo():String
    + getTematica():String
    + getTextoRespuesta(): String
}

}

Pregunta <|.down. PreguntaVF
Pregunta <|.down. PreguntaVFPenalidad
Pregunta <|.down. PreguntaMC
Pregunta <|.left. PreguntaOC
Pregunta <|.right. PreguntaGC
Pregunta <|.up.. PreguntaMCParcial
Pregunta <|.up.. PreguntaMCPenalidad

@enduml